feat(ui): add header to tables
defenseunicorns/uds-runtime pull request #106
Opened 2024-07-30 20:08 UTC by UncleGedd

## Description

...

## Related Issue

- #84

2024-07-30 22:03 UTC, UncleGedd commented on ui/src/lib/components/DataTable/component.svelte
> +  const flatRoutes = routes.flatMap((route) => {
Nobody look at this....it's super jank and tightly couples the view to the routes (we do this with Breadcrumbs but this feels nasty here)

Going to refactor and pass title + tooltipDesc as props to DataTable

2024-07-31 00:01 UTC, jeff-mccoy commented on ui/src/lib/components/DataTable/component.svelte
> +  const flatRoutes = routes.flatMap((route) => {
![image](https://github.com/user-attachments/assets/142871ac-23b5-420f-a7cd-a1b255bee693)

2024-07-31 12:56 UTC, TristanHoladay commented on ui/src/lib/components/DataTable/component.svelte
> +            data-tooltip-target="resource-tooltip"
not entirely sure, but you might not need these data attributes. in `ui/src/lib/features/k8s/configs/uds-exemptions/exemption-details/component.svelte` there's an example of  tooltip without them.

2024-07-31 13:05 UTC, jeff-mccoy commented on ui/src/lib/components/DataTable/component.svelte
> +            data-tooltip-target="resource-tooltip"
Yep those data attributes were for the flowbite js, but our tooltip is pure css if you have the right classes

2024-07-31 13:17 UTC, TristanHoladay commented on ui/src/lib/utils/descriptions.ts
> +  ClusterRoleBindings:
this wouldn't work for airgapped, but for connected environments would it be cool to have a link to each resource in the K8s docs?

2024-07-31 13:43 UTC, UncleGedd commented on ui/src/lib/utils/descriptions.ts
> +  ClusterRoleBindings:
Good be a nice feature down the line, we'll defer to the air gap use case for now

2024-07-31 20:32 UTC, Madeline-UX approved these changes
I sanction and approve these changes 
- change info icon to not filled
- change number to say "showing x of total"

2024-08-01 14:33 UTC, jeff-mccoy requested changes
I left a placeholder comment to see what I'm referring to, but this is every one of those files so bringing up to here instead:

--

This is preference--but feel this would be cleaner as two unique properties and set directly in this file where all presentation parts live for this view, something like 


```
  const name = "HorizontalPodAutoscaler"
  const description = "..."
```

For testing I'm not sure we really need to test every word of the description either vs just the string exists 🤔 but not sure on that. 

Realize that's different than how we did in [kfc](https://github.com/defenseunicorns/kubernetes-fluent-client/blob/main/src/kinds.ts), but think makes more sense in the same file for this project. 

I also wouldn't be object to skipping variable declaration and putting on the component prop directly if it was still readable.

2024-08-01 14:33 UTC, jeff-mccoy commented on ui/src/lib/components/k8s/DataTable/component.svelte
> +    isFiltering = !!($search || $searchBy != 'Anywhere' || $namespace)
I wouldn't include searchby as it only has meaning if search has contents

2024-08-01 14:33 UTC, jeff-mccoy commented on ui/src/lib/features/k8s/cluster-ops/hpa/component.svelte
> +  const nameAndDesc: NameAndDesc = {
Placeholder comment to reference in PR review

2024-08-01 14:41 UTC, UncleGedd commented
> For testing I'm not sure we really need to test every word of the description either vs just the string exists 🤔 but not sure on that.

The goal of the testing  this was to ensure the descriptions matched up to something in `descriptions.ts` (esp since it was generated by 🤖 )

2024-08-01 14:43 UTC, UncleGedd commented on ui/src/lib/components/k8s/DataTable/component.svelte
> +    isFiltering = !!($search || $searchBy != 'Anywhere' || $namespace)
removed

2024-08-01 14:52 UTC, UncleGedd commented on ui/src/lib/features/k8s/cluster-ops/hpa/component.svelte
> +  const nameAndDesc: NameAndDesc = {
updated!

2024-08-01 16:55 UTC, jeff-mccoy approved these changes

2024-08-01 16:55 UTC, merged