feat: add pod disruption budgets view
defenseunicorns/uds-runtime pull request #79
Opened 2024-07-25 19:20 UTC by TristanHoladay

## Description
Add api and view for pod disruption budgets

## Related Issue

- #48

2024-07-25 21:07 UTC, decleaver commented on ui/src/lib/features/k8s/cluster-ops/pod-disruption-budgets/component.svelte
> +    ['min_available'],
just missing namespace

2024-07-26 14:47 UTC, TristanHoladay commented
![Screenshot from 2024-07-26 08-43-49](https://github.com/user-attachments/assets/12c6b1e1-8f6c-488f-bcd2-d17a078ddadc)

2024-07-26 18:15 UTC, decleaver commented on pkg/api/resources/cache.go
> +	policyV1 "k8s.io/api/policy/v1" // Add this line to import the missing package
can remove this comment, everything else looks good though!

2024-07-26 18:34 UTC, TristanHoladay commented on pkg/api/resources/cache.go
> +	policyV1 "k8s.io/api/policy/v1" // Add this line to import the missing package
naw, i want to let readers know exactly why i used that import .... :smile: Thanks, @decleaver

2024-07-26 20:09 UTC, jeff-mccoy requested changes
tiny typo

2024-07-26 20:09 UTC, jeff-mccoy commented on ui/src/lib/features/k8s/cluster-ops/pod-disruption-budgets/store.ts
> +  // needs dense=true to get thhe min_available and max_unavailable fields from spec
```suggestion
  // needs dense=true to get the min_available and max_unavailable fields from spec
```

2024-07-26 20:09 UTC, jeff-mccoy commented
Some merge conflicts

2024-07-27 02:50 UTC, jeff-mccoy approved these changes

2024-07-27 02:51 UTC, merged

2024-07-27 02:52 UTC, Madeline-UX commented
@TristanHoladay your screen is so big yet the screenshot was so small. I'm unable to see enough detail to do UX review lol but the shapes look about right. 🤣

2024-07-28 01:27 UTC, TristanHoladay commented
is this better @Madeline-UX? i used dev tools to show it as 1920 x 1080 ...
![Screenshot from 2024-07-27 19-26-30](https://github.com/user-attachments/assets/657dccb2-716c-4500-9aeb-082a334f1092)